name: Image Build and Push

on:
  workflow_dispatch:


jobs:
    build-and-push-:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Azure Docker Registry
            uses: azure/docker-login@v2
            with:
              login-server: creuwbfcommonsp.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

          - name: Build and push Docker image
            run: |
              docker build . -t creuwbfcommonsp.azurecr.io/infrastructure/github-runner:${{ github.sha }} \
              --build-arg APP_ID=${{ secrets.APP_ID }} \
              --build-arg APP_PRIVATE_KEY=${{ secrets.APP_PRIVATE_KEY }} \
              --build-arg GH_OWNER=${{ vars.GH_OWNER }} \
              --build-arg GH_REPO=${{ vars.GH_REPO }} \
          
          - name: Update CONTAINER_IMAGE_NAME variable
            env:
              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
            run: |
              curl -X PATCH \
              -H "Authorization: Bearer $INSTALLATION_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/variables/CONTAINER_IMAGE_NAME" \
              -d "{\"value\":\"${{ github.sha }}\"}" \
              || { echo "Failed to update variable"; exit 1; }

#          - name: Trigger Deployment Workflow
#            env:
#              INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
#            run: |
#              # Trigger the deployment workflow in the current repository
#              curl -X POST \
#                -H "Authorization: Bearer $INSTALLATION_TOKEN" \
#                -H "Accept: application/vnd.github+json" \
#                "https://api.github.com/repos/${{ github.repository }}/actions/workflows/prod-deploy-infra.yml/dispatches" \
#                -d '{"ref":"main"}' \
#                || { echo "Failed to trigger deployment workflow"; exit 1; }
